#! /bin/bash
if [ ! -f sink.js/sink.js ];
then
    cd sink.js
    make
    cd ../
fi

juicer merge core/*.js dsp/*.js operators/*.js pattern/*.js scale/*.js tuning/*.js sink.js/*.js -f -s -m none -o audiolet/Audiolet.js
