#! /bin/bash
if [ $# -ne 1 ]
then
    echo "Usage: release RELEASE_NUMBER"
    exit
fi

RELEASE_NAME="Audiolet-"$1
TARBALL_NAME=$RELEASE_NAME".tar.gz"
ZIP_NAME=$RELEASE_NAME".zip"

# Create release folder
mkdir releases/$RELEASE_NAME

# Do a build
./build
./dist

# Copy audiolet to root directory
cp audiolet/* releases/$RELEASE_NAME

# Copy libraries in folders
cp -r mootools releases/$RELEASE_NAME
cp -r firebugx releases/$RELEASE_NAME

# Copy license
cp LICENSE releases/$RELEASE_NAME

# Copy examples
cp -r ../examples releases/$RELEASE_NAME

# Replace ../../src/webglet with ../..
sed -i "s/\.\.\/\.\.\/src\/audiolet/\.\.\/\.\./g" releases/$RELEASE_NAME/examples/*/*.htm
# Replace ../../src with ../..
sed -i "s/\.\.\/\.\.\/src/\.\.\/\.\./g" releases/$RELEASE_NAME/examples/*/*.htm

# Create tarball and zip
cd releases
tar cfz $TARBALL_NAME $RELEASE_NAME
zip -r $ZIP_NAME $RELEASE_NAME


echo "Don't forget to branch and tag the release if it looks good!"
